### ISSUE TITLE
Any plan to release a binary?

### ISSUE THREAD

**Issue by jjhidalgar** [UeharaYou/HiddenBar#2]
^

Thanks for updating this project.

**Comment by UeharaYou** [comment]
Hello @jaimehrubiks. Thanks for your encouragement. But for now, I'm not planning to publish a pre-built binary. Please download the source code and build it instead. Pre-built binaries might be available after further fine polishing should be done. 

> **Here're some mumble-jumble for why, I hope you could understand.**
The reason I chose not to include any pre-built binaries mainly because a chain of security and trust. Of course, it doesn't mean that a release build can't be exported. I can just pack my builds into a zip file and upload to a GitHub release, but it will certainly be flagged by GateKeeper since it's not notarized (only signed with my local cert), unless such security feature is bypassed. Disabling / bypassing GateKeeper is considered a risky behavior for potentially compromising personal privacy and info safety, and that should be regarded by all users. For this reason, along with that paying Apple a dev enrollment now is not feasible, the only way that suits me is the primitive way: distribute the source code only. It is a premature, but effective way to gain trust without a 3rd party adjudication, since users can inspect the code before compiling it.

Thank you so much for reading through this message. Feel free to occasionally drop by to see what's happening here for further updates of "Hidden Bar (UM)".

This issue will stay open awaiting for further updates.

**Comment by rainyskye** [comment]
Seeing you've added the `help wanted` label, would you be interested in handing off distribution to someone else?

**Comment by awkj** [comment]
> Hello @jaimehrubiks. Thanks for your encouragement. But for now, I'm not planning to publish a pre-built binary. Please download the source code and build it instead. Pre-built binaries might be available after further fine polishing should be done.
> 
> > **Here're some mumble-jumble for why, I hope you could understand.**
> > The reason I chose not to include any pre-built binaries mainly because a chain of security and trust. Of course, it doesn't mean that a release build can't be exported. I can just pack my builds into a zip file and upload to a GitHub release, but it will certainly be flagged by GateKeeper since it's not notarized (only signed with my local cert), unless such security feature is bypassed. Disabling / bypassing GateKeeper is considered a risky behavior for potentially compromising personal privacy and info safety, and that should be regarded by all users. For this reason, along with that paying Apple a dev enrollment now is not feasible, the only way that suits me is the primitive way: distribute the source code only. It is a premature, but effective way to gain trust without a 3rd party adjudication, since users can inspect the code before compiling it.
> 
> Thank you so much for reading through this message. Feel free to occasionally drop by to see what's happening here for further updates of "Hidden Bar (UM)".
> 
> This issue will stay open awaiting for further updates.

great!, we wanting you ! expect first release version

**Comment by UeharaYou** [comment]
@rainyskye Hello there, thank you for your help! 

It is authorized to distribute copies with conformation of the current LICENSE (MIT).  You might also consider creating a PR for having your binary shared here.

**Comment by rainyskye** [comment]
> The reason I chose not to include any pre-built binaries mainly because a chain of security and trust. Of course, it doesn't mean that a release build can't be exported. I can just pack my builds into a zip file and upload to a GitHub release, but it will certainly be flagged by GateKeeper since it's not notarized (only signed with my local cert), unless such security feature is bypassed. Disabling / bypassing GateKeeper is considered a risky behavior for potentially compromising personal privacy and info safety, and that should be regarded by all users.

Btw, you don't have to fully bypass Gatekeeper to do this, you can just right click and click `Open`.

**Comment by rainyskye** [comment]
> It is authorized to distribute copies with conformation of the current LICENSE (MIT). You might also consider creating a PR for having your binary shared here.

I might end up setting up some kind of CI, I tried setting it up quickly but haven't messed with Xcode/macOS CI on GitHub Actions before so I might need to mess around with it more or use something I'm more familiar with.

**Comment by UeharaYou** [comment]
> I might end up setting up some kind of CI, I tried setting it up quickly but haven't messed with Xcode/macOS CI on GitHub Actions before so I might need to mess around with it more or use something I'm more familiar with.

CI/Automatic packaging is not the major problem, the code-signing is. Self-built packages only works on local machines, and cannot be distributed without being notarized (gatekeeper reacts with that). And Apple charge developer annually for just that. So the cheapest solution for that is to just release the source code and let user build it themselves.

**Comment by tcurdt** [comment]
> CI/Automatic packaging is not the major problem, the code-signing is. Self-built packages only works on local machines, and cannot be distributed without being notarized (gatekeeper reacts with that). And Apple charge developer annually for just that. So the cheapest solution for that is to just release the source code and let user build it themselves.

Those are two very different things. Most users can easily bypass the gatekeeper restrictions (with a right click). Fewer people manage to build the app. Making a build available (especially via brew) would be nice - and cheap. Many open source projects do it like that.

Why not let @rainyskye contribute a PR for that?

**Comment by UeharaYou** [comment]
> Those are two very different things. Most users can easily bypass the gatekeeper restrictions (with a right click). Fewer people manage to build the app. Making a build available (especially via brew) would be nice - and cheap. Many open source projects do it like that.
> 
> 
> 
> Why not let @rainyskye contribute a PR for that?

Hi there @tcurdt, you are right. I should find other ways to establish trustworthiness for the prebuilt binaries. An CI workflow for building the binary has been drafted, just not installed into GitHub actions. It can be made available very easily. 

But for uploading to brew, there're still issues. In short, this fork is not popular enough for the criteria of acceptance. So unfortunately for the period of time, the app is not available in brew.

**Comment by tcurdt** [comment]
> But for uploading to brew, there're still issues. In short, this fork is not popular enough for the criteria of acceptance. So unfortunately for the period of time, the app is not available in brew.

A custom tap could be an easy way around that.

I don't want to sound pushy but just want to point out the possible options.

**Comment by UeharaYou** [comment]
> A custom tap could be an easy way around that.

It seems to be a good solution. 😄

**Comment by Cassian-Andor** [comment]
I would agree with the custom tap, if possible. I found this project recently (well, the OG), and was starting to use to see if it's a viable alternative to Bartender, but the lack of updates threw me off, until I found this fork by chance.

**Comment by Karrq** [comment]
+1 on the brew tap with a cask, would make installation very much easier

**Comment by UeharaYou** [comment]
Right now non-notarized version is available on Github release.
